version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:490004619903:task-definition/ECS-Task-definition-family-service-uusj7nhx:4"
        LoadBalancerInfo:
          ContainerName: "app"
          ContainerPort: 80
